### ISSUE TITLE
What is being used to Generate the id3 data?

### ISSUE THREAD

**Issue by meandavejustice** [geelen/x-gif#1]
Trying to run the `audio.html` demo, I've added my own track and am able to get that to load. I was wondering what utility you are using to get the metadata you are loading with `lose_yourself_to_dance.json`? I found a little tool called [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/) to do my own conversion, but it does not generate an array of "songs".

Thanks! x-gif is fucking awesome!

**Comment by geelen** [comment]
Hit up djgif-echonest-proxy.herokuapp.com

That's where the data's coming from. I need an example track that's
creative commons to show off with x-gif stuff. For the demo at MWJS today I
used:
http://djgif-echonest-proxy.herokuapp.com/search?artist=daft%20punk&title=lose%20yourself%20to%20dance

Save that as lose_yourself_to_dance.json and find that mp3 from somewhere
and you can recreate. But yeah, when I find a good legal track to demo with
I'll update the example.

-glen

**Comment by meandavejustice** [comment]
Awesome, thanks for the quick response!
