### ISSUE TITLE
x-gif is not showing

### ISSUE THREAD

**Issue by msalehipro** [geelen/x-gif#16]
Hi...
There is a problem !
x-gif is not showing for me... instead of it, the < x-gif > full tag with other attributes is showing...
![untitled](https://cloud.githubusercontent.com/assets/5165298/3064918/dc8ab098-e25a-11e3-827f-0e6a9ac47443.png)

I've tried to refresh the page but the problem does not go away...

**Comment by nelsonpecora** [comment]
@MSalehi what browser / version are you using?

**Comment by msalehipro** [comment]
Mozilla Firefox 31.0 , does it support custom elements ?!
i tried to test it again in Google Chrome 36.0.1985.125... but already it doesn't work :(

**Comment by marcysutton** [comment]
The page shows example usage below each GIF. That just means it wasn't loading for you. Do you get any errors? Are you trying to deep link a GIF other than the one the page loads with? 

![screen shot 2014-09-06 at 11 39 17 pm](https://cloud.githubusercontent.com/assets/1045233/4177736/caec107c-3659-11e4-8a79-50dc138b9dca.png)

**Comment by msalehipro** [comment]
Thanks a lot everyone!, My problem fixed.
