### ISSUE TITLE
Flickering after first animation cycle in Chrome 37

### ISSUE THREAD

**Issue by Henni** [geelen/x-gif#20]
The animation of one of the example gifs (http://i.imgur.com/m25uYzq.gif) on the demonstration page (http://geelen.github.io/x-gif/#/http://i.imgur.com/m25uYzq.gif) starts flickering after its first animation cycle has finished.
It seems as if after each frame a white frame is inserted.

I'm testing this with the current beta version of Chrome on Ubuntu:
Google Chrome:  37.0.2062.20 (Official Build 283104) beta
OS:             Linux 
Blink:          537.36 (@178111)
JavaScript:     V8 3.27.34.6

I don't experience this issue on the current version of Firefox (31.0), so maybe it is a bug inside Chrome.

Let me know if you need further information.

**Comment by geelen** [comment]
That's super weird! I don't get it on Chrome 36 or 38 on OSX, nor on
Firefox. That's the only test GIF I have that uses the 'restore' value of
the 'disposal method' flag on each frame. It adds a class
'disposal-restore' to each frame that gets rendered. Maybe something weird
happens inside there.

Could you try Chrome Canary on your machine?

**Comment by Henni** [comment]
There is no Chrome Canary available for Linux.

As described earlier this issue appears after the first cycle of the animation.
Additionally after i update the window by scrolling, the animation works again for one cycle.

I had a look at the class "disposal-restore". After removing it manually from all frames with development tools the animation worked smoothly except this graphical glitch:
![x-gif](https://cloud.githubusercontent.com/assets/1267827/3702479/ed8e7768-13ff-11e4-9f8d-c7f268386021.png)
I guess removing this class leads to having multiple transparent pngs behind each other, right?

I hope this information helps.

**Comment by Henni** [comment]
This issue disappeared within the last two weeks.
It was probably fixed by changes in Chrome.
