### ISSUE TITLE
Self-closing tag

### ISSUE THREAD

**Issue by zlatanvasovic** [geelen/x-gif#7]
Syntax would be nicer if we use the `<x-gif ...>` instead of `<x-gif ...></x-gif>`. Thanks in advance.

**Comment by geelen** [comment]
Yeah, I would like that, but I came across this SO answer by @ebidel that indicates it's not possible: http://stackoverflow.com/questions/22393760/does-polymer-js-support-inner-svg-elements/22394618#22394618

So I think we're out of luck. `<x-gif></x-gif>` it is!

**Comment by zlatanvasovic** [comment]
:(

2014-03-22 21:51 GMT+01:00 Glen Maddern notifications@github.com:

> Closed #7 https://github.com/geelen/x-gif/issues/7.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/geelen/x-gif/issues/7
> .

## 

Zlatan Vasović - _ZDroid_
